export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SESSION_RESTORE_REQUEST = 'SESSION_RESTORE_REQUEST';
export const SESSION_RESTORE_SUCCESS = 'SESSION_RESTORE_SUCCESS';
export const SESSION_RESTORE_FAILURE = 'SESSION_RESTORE_FAILURE';